### ISSUE TITLE
???

### ISSUE THREAD

**Issue by jhuiry8** [Carbowix/Cleve#16]
[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.
      at Function.verifyString (C:\Users\piggy\Desktop\bot\node_modules\discord.js\src\util\Util.js:414:49)
      at MessagePayload.makeContent (C:\Users\piggy\Desktop\bot\node_modules\discord.js\src\structures\MessagePayload.js:113:22)
      at MessagePayload.resolveData (C:\Users\piggy\Desktop\bot\node_modules\discord.js\src\structures\MessagePayload.js:128:26)
      at TextChannel.send (C:\Users\piggy\Desktop\bot\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:165:32)
      at Message.reply (C:\Users\piggy\Desktop\bot\node_modules\discord.js\src\structures\Message.js:743:25)
      at Object.handleTalk (C:\Users\piggy\Desktop\bot\util.js:34:17)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    [Symbol(code)]: 'MESSAGE_CONTENT_TYPE'
  }
}  reason:  Message content must be a non-empty string.

**Comment by Carbowix** [comment]
This issue was patched already,  re download cleve.
