### ISSUE TITLE
????

### ISSUE THREAD

**Issue by jhuiry8** [Carbowix/Cleve#17]
c:\Users\piggy\Desktop\bot>node index.js
[CLEVE] Started and ready to chat!
[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.
      at Function.verifyString (c:\Users\piggy\Desktop\bot\node_modules\discord.js\src\util\Util.js:414:49)
      at MessagePayload.makeContent (c:\Users\piggy\Desktop\bot\node_modules\discord.js\src\structures\MessagePayload.js:113:22)
      at MessagePayload.resolveData (c:\Users\piggy\Desktop\bot\node_modules\discord.js\src\structures\MessagePayload.js:128:26)
      at TextChannel.send (c:\Users\piggy\Desktop\bot\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:165:32)
      at Message.reply (c:\Users\piggy\Desktop\bot\node_modules\discord.js\src\structures\Message.js:743:25)
      at Object.handleTalk (c:\Users\piggy\Desktop\bot\util.js:34:17)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    [Symbol(code)]: 'MESSAGE_CONTENT_TYPE'
  }
}  reason:  Message content must be a non-empty string.

**Comment by Carbowix** [comment]
Please stop creating an issue every single hour for the same error. Already told you to re-download the latest cleve again because this issue was patched.
