### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LolekLiam** [Carbowix/Cleve#18]
when i try to run, i get this error:

[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> HTTPError [ReferenceError]: AbortController is not defined
      at RequestHandler.execute (C:\Users\Liam\node_modules\discord.js\src\rest\RequestHandler.js:172:15)
      at RequestHandler.execute (C:\Users\Liam\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
      at RequestHandler.push (C:\Users\Liam\node_modules\discord.js\src\rest\RequestHandler.js:50:25)
      at async WebSocketManager.connect (C:\Users\Liam\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
      at async Client.login (C:\Users\Liam\node_modules\discord.js\src\client\Client.js:245:7) {
    code: 500,
    method: 'get',
    path: '/gateway/bot',
    requestData: { json: undefined, files: [] }
  }
}  reason:  AbortController is not defined

**Comment by LolekLiam** [comment]
cmon @Carbowix i need anwser

**Comment by Carbowix** [comment]
discord v13 requires node.js v16.6 or higher. Please refer to [this](https://stackoverflow.com/questions/68693319/why-am-i-getting-a-referenceerror-abortcontroller-is-not-defined-in-discord-js) for more details.
