### ISSUE TITLE
fatal error when attempting to send messages in discord

### ISSUE THREAD

**Issue by LcorpOfficial** [Carbowix/Cleve#22]
error when sending a message in any channel, used fresh install with npm. discord shows as typing for a second then no response.

```
[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.
      at Function.verifyString (/home/pi/node_modules/discord.js/src/util/Util.js:414:49)
      at MessagePayload.makeContent (/home/pi/node_modules/discord.js/src/structures/MessagePayload.js:113:22)
      at MessagePayload.resolveData (/home/pi/node_modules/discord.js/src/structures/MessagePayload.js:128:26)
      at TextChannel.send (/home/pi/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:165:32)
      at Message.reply (/home/pi/node_modules/discord.js/src/structures/Message.js:743:25)
      at Object.handleTalk (/home/pi/node_modules/clevy/util.js:34:17)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    [Symbol(code)]: 'MESSAGE_CONTENT_TYPE'
  }
}  reason:  Message content must be a non-empty string.

```

**Comment by Carbowix** [comment]
Make sure to clone the latest version of **Cleve**  repo. and follow the instructions carefully then everything will work fine. Always check if your issue exists before posting another [replicate](https://github.com/Carbowix/Cleve/issues/14)

**Comment by LcorpOfficial** [comment]
sorry, got it! it was actually due to a nested discord.js not updating issue
