### ISSUE TITLE
Cannot find module 'node:events'

### ISSUE THREAD

**Issue by HAGAI123** [Carbowix/Cleve#35]
root@mail:/home/botd# node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:events'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/botd/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Carbowix** [comment]
download the latest [Node.js](https://nodejs.org/en/download/)

**Comment by HAGAI123** [comment]
root@mail:~# node -v
v17.4.0

**Comment by Carbowix** [comment]
Works fine here with the same LTS version you listed. Hm, try to re-install **discord.js** by `npm remove discord.js` and `npm install discord.js`. If it still doesn't work then try to make sure the bot's workspace recognizes the machine with `node.js v16.6+`.
