### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by Natzalia** [Carbowix/Cleve#37]
```js
[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> DiscordAPIError: Cannot send an empty message
      at RequestHandler.execute (/home/runner/AI/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (/home/runner/AI/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
      at async TextChannel.send (/home/runner/AI/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:175:15) {
    method: 'post',
    path: '/channels/XXXXXXXXXX/messages',
    code: 50006,
    httpStatus: 400,
    requestData: { json: [Object], files: [] }
  }
}  reason:  Cannot send an empty message
```

**Comment by Carbowix** [comment]
Seems like you didn't update Cleve to the latest version *or* your `misc/config.json` is not configured properly. Make sure to follow the steps carefully like in the [README](https://github.com/Carbowix/Cleve/blob/master/README.md).
